"""Guards on `scripts/run_load_sweep.py`, and specifically on redrawing without measuring.

This sweep was the one figure in the repository that could not be redrawn from committed
inputs: it measured and drew in a single pass, so reproducing the picture meant running
the models again. `benchmarks.md` says the measure/draw separation is the point, a run
drifts by up to 10% back to back, so a figure regenerated by re-measuring disagrees with
the tables beside it for reasons that have nothing to do with the code, and this script
was the exception to it.

`--replot` closes that. What these check is the part that makes the redraw trustworthy:
that it needs nothing but the CSV and the committed serving config, that it refuses
politely when the CSV is absent instead of drawing an empty figure, and that the title it
derives is the one the measured run derived, so a replot cannot quietly retitle the
picture with a different capacity.

`results/load_sweep.csv` is committed, so these run on a fresh checkout instead of
skipping there.
"""

import os
import struct
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

pytest.importorskip("matplotlib", reason="figures need the bench extra")
pytest.importorskip("pandas", reason="the sweep frame needs the bench extra")

import run_load_sweep as sweep  # noqa: E402

CONFIG = ROOT / "configs" / "serving.yaml"
MEASURED_CSV = ROOT / "results" / "load_sweep.csv"
COMMITTED_FIGURE = ROOT / "docs" / "img" / "load_sweep.png"

HEADER = (
    "policy,attempted,served,rejected,completion_rate,deadline_hit_rate,latency_p50_ms,"
    "latency_p95_ms,latency_p99_ms,mean_cost_per_served,goodput_rps,target_utilisation,"
    "arrival_rate_rps,variant_mix"
)


def _row(policy: str, utilisation: float, arrival: float) -> str:
    return (
        f"{policy},100,99,1,0.99,0.95,16.0,34.0,53.0,1.0,120.0,{utilisation},{arrival},"
        f'"{{""distilbert_fp32"": 99}}"'
    )


def _csv(path: Path) -> Path:
    path.write_text(
        "\n".join(
            [
                HEADER,
                _row("accurate-only", 0.4, 124.1),
                _row("adaptive", 0.4, 124.1),
                _row("accurate-only", 0.8, 248.2),
                _row("adaptive", 0.8, 248.2),
            ]
        )
        + "\n"
    )
    return path


def test_replot_draws_from_a_csv_and_the_config_alone(tmp_path, monkeypatch):
    """No model directory, no ONNX Runtime pool, no measurement."""
    figure = tmp_path / "load_sweep.png"
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "run_load_sweep.py",
            "--replot",
            "--serving-config",
            str(CONFIG),
            "--output",
            str(_csv(tmp_path / "load_sweep.csv")),
            "--figure",
            str(figure),
        ],
    )
    assert sweep.main() == 0
    assert figure.is_file()
    assert figure.stat().st_size > 10_000


def test_replot_refuses_a_missing_csv_and_says_what_to_run(tmp_path, monkeypatch):
    """An absent CSV should not draw four empty panels."""
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "run_load_sweep.py",
            "--replot",
            "--serving-config",
            str(CONFIG),
            "--output",
            str(tmp_path / "absent.csv"),
            "--figure",
            str(tmp_path / "figure.png"),
        ],
    )
    with pytest.raises(SystemExit, match="nothing to replot"):
        sweep.main()


def test_the_capacity_in_the_title_is_the_one_the_csv_was_measured_at():
    """The title is derived from the config, and the CSV records the rate it was driven
    at. If those disagreed, a replot would retitle the figure with a capacity the numbers
    underneath it were never measured against.
    """
    pandas = pytest.importorskip("pandas")
    variants, _deadline_ms, workers = sweep._load_profiles(CONFIG)
    variants.sort(key=lambda variant: -variant.accuracy)
    from_config = workers * 1000.0 / variants[0].service_time_ms

    frame = pandas.read_csv(MEASURED_CSV)
    from_csv = frame["arrival_rate_rps"] / frame["target_utilisation"]
    assert from_csv.round(3).nunique() == 1, "the sweep did not hold capacity fixed"
    assert abs(from_csv.iloc[0] - from_config) < 0.01


def _png_size(path: Path) -> tuple[int, int]:
    """Pixel dimensions straight out of the IHDR chunk.

    Done by hand instead of with Pillow, which is in the `research` extra instead of
    `bench`, and a figure test should not drag a model-export dependency in behind it.
    """
    header = path.read_bytes()[:24]
    assert header[:8] == b"\x89PNG\r\n\x1a\n", f"{path} is not a PNG"
    return struct.unpack(">II", header[16:24])


def test_replot_reproduces_the_committed_figure(tmp_path, monkeypatch):
    """Committed CSV plus committed config redraws the committed figure.

    Dimensions instead of bytes, and that is not laziness. A PNG's bytes depend on the
    freetype build that rasterised its text: the same code and the same data give
    different bytes under freetype 2.6.1 and 2.14.3, which ship with matplotlib 3.10 and
    3.11. Asserting byte equality would fail for almost everyone who checked this
    repository out, which is the opposite of what a reproducibility test is for.

    Dimensions still catch what actually goes wrong here, a changed figsize, dpi, or
    layout rect, and the numeric agreement between the CSV and the config is checked
    above. Set `ANYTIME_FIGURE_BYTES=1` to demand byte equality as well, which is worth
    doing on the machine the committed figures were drawn on and nowhere else.
    """
    figure = tmp_path / "load_sweep.png"
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "run_load_sweep.py",
            "--replot",
            "--serving-config",
            str(CONFIG),
            "--output",
            str(MEASURED_CSV),
            "--figure",
            str(figure),
        ],
    )
    assert sweep.main() == 0
    assert _png_size(figure) == _png_size(COMMITTED_FIGURE)
    if os.environ.get("ANYTIME_FIGURE_BYTES") == "1":
        assert figure.read_bytes() == COMMITTED_FIGURE.read_bytes()
